### ISSUE TITLE
No localization for Spell Weaver

### ISSUE THREAD

**Issue by Jonathing** [tkdberger/fictional-meme#1]
Make sure that you have the localization in the language files you are using.
![http://i.imgur.com/6tkysMn.png](http://i.imgur.com/6tkysMn.png)

**Comment by edwanvi** [comment]
Did you read the release notes?

>Some alpha content that you shouldn't use yet because **it's unlocalized** and unfinished was added.

Anyway it's getting fixed soon.

**Comment by Jonathing** [comment]
Ah sorry about that.
