### ISSUE TITLE
Ender-Infused Leaping Boots don't allow critical hits

### ISSUE THREAD

**Issue by Jonathing** [tkdberger/fictional-meme#2]
With the boots equipped, you can't make critical hits. However, if they are unequipped, you can then make critical hits. Plain and simple.
https://youtu.be/23T3BCHA5qk

**Comment by edwanvi** [comment]
huh. that's odd.  Let me make sure I can reproduce this one when I get home and I'll give you an update.  From the video it looks like you may have hit the ground before actually hitting.  But I could be wrong.

**Comment by edwanvi** [comment]
Would ya look at that.

>The requirements for a melee critical hit are:
> * The player must be falling.

1. `/gamemode c`
2. get boots
3. fly above thing
4. fall
5. hit thing on fall down
6. see crit particles

I think it's just hard to get a critical hit. Maybe.

**Comment by edwanvi** [comment]
Also works in survival. Yeah, this is just a case of "crits are hard."
